### PR TITLE
V2 SVG Deserializer

### LINKED ISSUE #439: SVG Import fails TypeError: right-hand side of 'in' should be an object, got undefined
## Expected Behavior
SVG import should work

## Actual Behavior
```
TypeError: right-hand side of 'in' should be an object, got undefined
Line: 24684,col: 0
(blob:https://www.openjscad.org/8e04e735-e15c-cd44-9431-127e3c824624)
```

## Steps to Reproduce the Problem

  1. Drag and Drop http://wiki.bitplan.com/images/wiki/7/7a/BITPlanLogo2012FontLess.svg
or try https://openjscad.org/#http://wiki.bitplan.com/images/wiki/7/7a/BITPlanLogo2012FontLess.svg

## Specifications

  - Version: 1.10.0
  - Platform: MacOS 10.3.6
  - Environment: Firefox 65

### LINKED ISSUE #460: SVG import should work for a logo example
## Expected Behavior
SVG import should work

## Actual Behavior
```
//
  // producer: OpenJSCAD.org 1.9.0 SVG Importer
  // date: Mon Aug 26 2019 11:14:38 GMT+0200 (Mitteleuropäische Sommerzeit)
  // source: BITPlanLogo2012FontLess.svg
  //
  function main(params) {
  var cag0 = new CAG();
    var cag1 = new CAG();
      var cag2 = new CAG();
        var cag3 = new CAG();
          var cag4 = new CAG();
        var cag30 = cag4;
        cag3 = cag3.union(cag30);
      var cag20 = cag3;
      cag20 = cag20.translate([5.644443999999999,-5.644443999999999]);
      cag2 = cag2.union(cag20);
    var cag10 = cag2;
    cag1 = cag1.union(cag10);
      var cag2 = new CAG();
        var cag3 = new CAG();
          var cag4 = new CAG();
        var cag30 = cag4;
        cag30 = cag30.translate([0,0]);
        cag3 = cag3.union(cag30);
      var cag20 = cag3;
      cag2 = cag2.union(cag20);
    var cag11 = cag2;
    cag11 = cag11.translate([342.05330639999994,-279.399978]);
    cag1 = cag1.union(cag11);
  var cag00 = cag1;
  cag00 = cag00.scale([0.29333,0.29333]);
  cag00 = cag00.translate([-47.977774,-10.1599992]);
  cag0 = cag0.union(cag00);
  return cag0;
}
```

does not show as 
grafik

## Steps to Reproduce the Problem

  1. Drag and Drop http://wiki.bitplan.com/images/wiki/7/7a/BITPlanLogo2012FontLess.svg
or try https://openjscad.org/#http://wiki.bitplan.com/images/wiki/7/7a/BITPlanLogo2012FontLess.svg

## Specifications

  - Version: 1.10.0
  - Platform: MacOS 10.3.6
  - Environment: Firefox 65

### PR DESCRIPTION
**Pull request by z3dev**
This pull request updates the SVG deserializer to use CSG V2 API, as well as translate to CSG V2 API. The goals of this pull request are:
- [X] Update to use CSG V2 API
- [X] Update code up to JSCAD coding standards
- [X] Add test suites to complete coverage, 86.16% coverage (73.59 instantiate, 96.83% translate)

New Features:
- support for colors.
- support for 1D (default) or 2D targets.

Fixes issue #439 and issue jscad/io#57 
Fixes issue #460 
Fixes issues with relative quadratic beziers in paths

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

File: packages/io/svg-deserializer/index.js [hunk 1]
```diff
@@ -131,85 +140,87 @@ const objectify = function (group) {
...
+    shapes = shapes.map((shape) => {
+      if ('transforms' in obj) {
+        // NOTE: SVG specifications require that transforms are applied in the order given.
+        // But these are applied in the order as required by the CSG library
+        let tr
+        let ts
+        let tt
+        for (let j = 0; j < obj.transforms.length; j++) {
+          const t = obj.transforms[j]
+          if ('rotate' in t) { tr = t }
```
Comment (kaosat-dev) [inline packages/io/svg-deserializer/index.js]: these need to be changed, we do not have prototype methods anymore in V2
or wait where do the transforms come from in this ?

File: packages/io/svg-deserializer/index.js [hunk 2]
```diff
@@ -220,50 +231,51 @@ const codify = function (group) {
...
-      if (tt !== null) {
+      if (tt) {
         const x = cagLengthX(tt.translate[0], svgUnitsPmm, svgUnitsX)
         const y = (0 - cagLengthY(tt.translate[1], svgUnitsPmm, svgUnitsY))
-        code += indent + on + ' = ' + on + '.translate([' + x + ',' + y + ']);\n'
+        code += `${indent}${on} = transforms.translate([${x}, ${y}, 0], ${on})\n`
       }
     }
-    code += indent + ln + ' = ' + ln + '.union(' + on + ');\n'
+    if (target === '1D' && obj.stroke) {
```
Comment (kaosat-dev) [inline packages/io/svg-deserializer/index.js]: I do not quite understand how this works, could you explain it a bit please? thanks :)

File: packages/io/svg-deserializer/index.js (hunk 1 above)
Comment (kaosat-dev) [reply packages/io/svg-deserializer/index.js]: (if they are on the svg objects and not CSG/Jscad, feel free to ignore)

File: packages/io/svg-deserializer/shapesMapCsg.js [hunk 3]
```diff
@@ -1,15 +1,13 @@
-const {CSG, CAG} = require('@jscad/csg')
-const {svg2cagX, svg2cagY, cagLengthX, cagLengthY, cagLengthP, reflect, groupValue} = require('./helpers')
-const {cssPxUnit} = require('./constants')
+const { geometry, primitives } = require('@jscad/csg')
```
Comment (kaosat-dev) [inline packages/io/svg-deserializer/shapesMapCsg.js]: perhaps this file can be renamed to shapesMapGeomety ? or shapesMapInstanciate ?

Comment (kaosat-dev) [inline packages/io/svg-deserializer/shapesMapCsg.js]: the import needs to be updated

File: packages/io/svg-deserializer/tests/instantiate.test.js [hunk 4]
```diff
@@ -0,0 +1,269 @@
+const test = require('ava')
```
Comment (kaosat-dev) [inline packages/io/svg-deserializer/tests/instantiate.test.js]: nice

File: packages/io/svg-deserializer/tests/inkscape.test.js [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+  let count = 0
+  let index = string.indexOf(search)
+  while (index !== -1) {
+    count++
+    index = string.indexOf(search, index + 1)
+  }
+  return count
+}
+
+test('deserialize : translate svg produced by inkscape to script', function (t) {
```
Comment (kaosat-dev) [inline packages/io/svg-deserializer/tests/inkscape.test.js]: while I admire the effort, I do not quite understand why there is a need for inkscape specific test ? are there SVG variations ?

Comment (z3dev) [reply packages/io/svg-deserializer/tests/inkscape.test.js]: Seems so as there was a fix for this.

https://github.com/jscad/io/pull/72

File: packages/io/svg-deserializer/.gitignore [hunk 6]
```diff
@@ -0,0 +1,8 @@
+node_modules
```
[the remark this answers is not in the document]
Comment (z3dev) [reply packages/io/svg-deserializer/.gitignore]: Done

File: packages/io/svg-deserializer/README.md [hunk 7]
```diff
@@ -1,24 +1,21 @@
 ## @jscad/svg-deserializer
 
-> svg deserializer for the jscad project
+> Deserializer of SVG data to CSG geometries
```
[the remark this answers is not in the document]
Comment (z3dev) [reply packages/io/svg-deserializer/README.md]: Done

File: packages/io/svg-deserializer/index.js [hunk 8]
```diff
@@ -11,61 +11,65 @@ All code released under MIT license
...
+* @return {string|[geometry]} either a string (jscad script) or a set of geometries
 */
-const deserialize = function (input, filename, options) {
+const deserialize = (input, filename, options) => {
   const defaults = {
-    output: 'jscad'
+    addMetaData: true,
+    output: 'script',
+    pxPmm: require('./constants').pxPmm,
+    target: '1D', // target - 2D geometry, or 1D geometry (paths)
```
[the remark this answers is not in the document]
Comment (z3dev) [reply packages/io/svg-deserializer/index.js]: Any suggestions on what to call the 'target'? Maybe 'paths' versus 'geom2'?

File: packages/io/svg-deserializer/shapesMapCsg.js (hunk 3 above)
Comment (z3dev) [reply packages/io/svg-deserializer/shapesMapCsg.js]: Done

Comment (z3dev) [reply packages/io/svg-deserializer/shapesMapCsg.js]: Done

File: packages/io/svg-deserializer/tests/inkscape.test.js (hunk 5 above)
Comment (kaosat-dev) [reply packages/io/svg-deserializer/tests/inkscape.test.js]: good point !

File: packages/io/svg-deserializer/index.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (kaosat-dev) [reply packages/io/svg-deserializer/index.js]: yes  sounds good !
perhaps both singular or both plural ? ie
- geometries & paths
- geom2 & path

File: packages/io/svg-deserializer/toArray.js [hunk 9]
```diff
@@ -0,0 +1,9 @@
+/* converts input data to array if it is not already an array */
```
Comment (kaosat-dev) [inline packages/io/svg-deserializer/toArray.js]: we do not have this somewhere already ?

File: packages/io/svg-deserializer/index.js (hunk 2 above)
Comment (z3dev) [reply packages/io/svg-deserializer/index.js]: Basically, SVG stroke is used for color() on path2 objects, which SVG fill is used for color() on geom2 objects.

File: packages/io/svg-deserializer/index.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (z3dev) [reply packages/io/svg-deserializer/index.js]: Done

File: packages/io/svg-deserializer/toArray.js (hunk 9 above)
Comment (z3dev) [reply packages/io/svg-deserializer/toArray.js]: Several actually... which is why I wasn't sure what would be appropriate.
- packages/core/utils/arrays.js
- packages/io/io-utils/arrays.js

I would prefere a common set of 'utils' that house our special routines for JavaScript compatibility / interoperability. We have several sets now, but maybe it's time to decide where these live going forward.

Maybe packages/utils should house these functions?

Comment (kaosat-dev) [reply packages/io/svg-deserializer/toArray.js]: I agree that it should be centralized but 'utils' is too vague, should be specific (to avoid having utils be a vague bag of everything): ie **arrayUtils** makes sense: I will add a note, we can tackle this later :)

File: packages/io/svg-deserializer/index.js (hunk 2 above)
Comment (kaosat-dev) [reply packages/io/svg-deserializer/index.js]: ok great!
