### PR TITLE
Fix 912 concat and appendArc

### LINKED ISSUE #912: `path2.concat()` of mirrored pair of paths followed by `extrudeRectangular` results in mesh with gaps
## Expected Behavior
Mirroring a path and concatenating it would result in a clean, deduplicated path ready to be extruded, with the same output as creating the path without mirroring (the output of which is shown on the right in the image below).

left: broken mesh version of chip clip model, right: resolved version

## Actual Behavior
The resulting mesh has gaps in it when attempting to mirror a path and then concatenate the mirrored and unmirrored versions together.

## Steps to Reproduce the Problem
The source code of both versions shown in the image can be found in [this CadHub project](https://cadhub.xyz/u/franknoirot/chip-clip-jscad/ide).
  1. Create a path
  2. Concatenate the path with a mirrored version of itself
  3. Extrude the path with `extrudeRectangular()`

## Specifications
  - Version: latest
  - Platform: CadHub
  - Environment: browser

### PR DESCRIPTION
**Pull request by hrgdavor**
fixes #912 
there is duplicate point at the joint, but not 100% equal `[1, -3]` vs `[0.9999999999999978, -3.0000000000000018]`

First issue is that path2.concat does not remove duplicate point when adding paths

Second issue is that appendArc does not produce the exact same endpoint as user asked for.

On route is to fix equality check using epsilon, and other is to force appendArc to respect the desired endpoint.

This PR  forces appendArc to respect the desired endpoint.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by hrgdavor** [comment]
image

File: packages/modeling/src/geometries/path2/appendArc.js [hunk 1]
```diff
@@ -130,6 +130,8 @@ const appendArc = (options, geometry) => {
       vec2.add(point, point, center)
       newpoints.push(point)
     }
+    // ensure end point is precisely what user gave as parameter
+    if (numsteps) newpoints.push(options.endpoint)
```
Comment (z3dev) [inline packages/modeling/src/geometries/path2/appendArc.js:134]: Nice!

File: packages/modeling/src/geometries/path2/concat.js [hunk 2]
```diff
@@ -1,8 +1,9 @@
 const fromPoints = require('./fromPoints')
```
Comment (z3dev) [inline packages/modeling/src/geometries/path2/concat.js:1]: For consistent style, let's add this require at the top.

`const vec2 = require('../../maths/vec2')`

File: packages/modeling/src/geometries/path2/concat.js [hunk 3]
```diff
@@ -1,8 +1,9 @@
...
 const toPoints = require('./toPoints')
-
+const equals = require('../../maths/vec2/equals')
 /**
  * Concatenate the given paths.
+ * If both contain the same point at the junction, merge it into one.
```
Comment (z3dev) [inline packages/modeling/src/geometries/path2/concat.js:6]: I think this is a comment for the code change, not for the API documentation.

File: packages/modeling/src/geometries/path2/concat.js [hunk 4]
```diff
@@ -24,7 +25,9 @@ const concat = (...paths) => {
   }
   let newpoints = []
   paths.forEach((path) => {
-    newpoints = newpoints.concat(toPoints(path))
+    const tmp = toPoints(path)
+    if (newpoints.length > 0 && equals(tmp[0], newpoints[newpoints.length - 1])) tmp.shift()
```
Comment (z3dev) [inline packages/modeling/src/geometries/path2/concat.js:29]: It's possible to concat paths that are empty, i.e. no points. So an addition check is required. Maybe the new test case should include an empty path.

**Review by z3dev — CHANGES_REQUESTED** [review]
Small changes requested, but looks good. A test case for the concat() change would be nice as well.

File: packages/modeling/src/geometries/path2/concat.js (hunk 3 above)
Comment (hrgdavor) [reply packages/modeling/src/geometries/path2/concat.js:6]: well, it is both :) ... may be good to leave it so end user knows the sideeffects of the concat.

File: packages/modeling/src/geometries/path2/concat.js (hunk 2 above)
Comment (hrgdavor) [reply packages/modeling/src/geometries/path2/concat.js:1]:
```js
const { equals } = require('../../maths/vec2')
```

**Review by z3dev — APPROVED** [review]
Looks good! Thanks.
