### PR TITLE
V2 fix web params

### LINKED ISSUE #654: V2 - Slider parameter ignores min/max attributes
## Expected Behavior
when adding a parameter of type slider
```    { name: 'count', type: 'slider', initial: 4, min: 2, max: 10, step: 1, caption: 'How many?' },
``` lets you select a number between 2 and 10

## Actual Behavior
The slider goes from 0 to 100

## Steps to Reproduce the Problem
Use the code above
 
## Specifications

  - Version: 2.0.0-alpha0
  - Platform: Mac
  - Environment: chrome

Fix is on the way.

### LINKED ISSUE #656: getParameterDefinitions fails for choice #V2
## Expected Behavior
changing choice parameter to render new object

## Actual Behavior
error  in console for chrome
[err.txt](https://github.com/jscad/OpenJSCAD.org/files/5103378/err.txt)
error in Firefox:
[err2.txt](https://github.com/jscad/OpenJSCAD.org/files/5103578/err2.txt)

## Steps to Reproduce the Problem

  1. npm run dev in packages/web
  2. open console F12
  3. drop a file  with this code to web interface

## Specifications
I use similar trick in v1 to have multiple parts in same file as part of design, maintaining values for the choice manually

```
const jscad = require('@jscad/modeling')
const { sphere, cylinderElliptic } = jscad.primitives;

var funcs = {};

funcs.Main1 = function(params){
  return cylinderElliptic({startRadius:[5,5], endRadius:[1,1], height:5})
}

funcs.Main2 = function(params){
  return cylinderElliptic({startRadius:[5,5], endRadius:[3,3], height:5})
 // return sphere();
}

function getParameterDefinitions() {
  var values = ['Main1', 'Main2'];
  var defs = [{ name:'piece', caption:'Piece', type:'choice', values, _initial: values[0]}];
  return defs;
}

function main(params){
  console.log('params',params, funcs);
  return funcs[params.piece || 'Main1']();
}

module.exports = { main , getParameterDefinitions}

```

  - Version: V2
  - Platform: any
  - Environment: Chrome Firefox

### PR DESCRIPTION
**Pull request by SimonClark**
Addresses a variety of issues with parameters:
- Choice parameters without captions now work.
- Groups can now be defaulted to closed.
- Groups don't re-open when another parameter is changed.
- Slider parameters now respect the min/max attributes.

## My test script (will be added to examples as part of the examples-refactor PR):
```
const {primitives} = require('@jscad/modeling')

const values = [3,4,5,6]
const captions = ["three","four","five","six"]

const getParameterDefinitions = () => {
  return [
    {name: 'group1', type: 'group', caption: 'Group 1: Text Entry'},
    {name: 'text', type: 'text', initial: '', size: 20, maxLength: 20, caption: 'Plain Text:', placeholder: '20 characters'},
    {name: 'int', type: 'int', initial: 20, min: 1, max: 100, step: 1, caption: 'Integer:'},
    {name: 'number', type: 'number', initial: 2.0, min: 1.0, max: 10.0, step: 0.1, caption: 'Number:'},
    {name: 'date', type: 'date', initial: '2020-01-01', min: '2020-01-01', max: '2030-12-31', caption: 'Date:', placeholder: 'YYYY-MM-DD'},
    {name: 'email', type: 'email', initial: 'me@example.com', caption: 'Email:'},
    {name: 'url', type: 'url', initial: 'www.z3d.jp', size: 40, maxLength: 40, caption: 'Url:', placeholder: '40 characters'},
    {name: 'password', type: 'password', initial: '', caption: 'Password:'},

    {name: 'group2', type: 'group', caption: 'Group 2: Interactive Controls'},
    {name: 'checkbox', type: 'checkbox', checked: true, initial: '20', caption: 'Checkbox:'},
    {name: 'color', type: 'color', initial: '#FFB431', caption: 'Color:'},
    {name: 'slider', type: 'slider', initial: 3, min: 1, max: 10, step: 1, caption: 'Slider:'},
    {name: 'choice1', type: 'choice', caption: 'Dropdown Menu:', values: [0, 1, 2, 3], captions: ['No', 'Yes', 'Maybe', 'So so'], initial: 2},
    {name: 'choice3', type: 'choice', caption: 'Dropdown Menu:', values: ['No', 'Yes', 'Maybe', 'So so'], initial: 2},
    {name: 'choice2', type: 'radio', caption: 'Radio Buttons:', values, captions, initial: 5},

    {name: 'group3', type: 'group', initial: 'closed', caption: 'Group 3: Initially Closed Group'},
    {name: 'checkbox2', type: 'checkbox', checked: true, initial: '20', caption: 'Optional Checkbox:'},
  ]
}

const main = (params) => {
  console.log(params)

  let obj1 = primitives.ellipsoid({radius: [30, 20, 10], segments: 32})

  return obj1
}

module.exports = {main, getParameterDefinitions}

```

FIxes #656 
Fixes #654 

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

### CODE REVIEW

File: packages/web/src/ui/views/parameterControls.js [hunk 1]
```diff
@@ -1,127 +1,167 @@
 const html = require('bel')
```
Comment (z3dev) [inline packages/web/src/ui/views/parameterControls.js:1]: I like the refactoring and changes. However, this file is just way too big.

I was wondering if this could be broken into the functional pieces as well. This will allow test cases to be created against each of the functional pieces as well.

File: packages/core/parameters/getParameterValuesFromUIControls.js [hunk 2]
```diff
@@ -49,7 +49,7 @@ const getParameterValuesFromUIControls = (paramControls, parameterDefinitions, o
         value = control.value
         break
       case 'group':
-        console.log('group')
+        value = control.className.includes('open') ? 'open' : 'closed'
```
Comment (z3dev) [inline packages/core/parameters/getParameterValuesFromUIControls.js:52]: Nice little enhancement. 👍

**Review by z3dev — CHANGES_REQUESTED** [review]

File: packages/web/src/ui/views/parameterControls.js (hunk 1 above)
Comment (SimonClark) [reply packages/web/src/ui/views/parameterControls.js:1]: Leaving as-is for now, I'll open an issue to refactor this.

**Review by z3dev — APPROVED** [review]
Changes look fine.
A new issue was created to track the request to refactor code.
