### PR TITLE
V2 : fix loading of designs from remote URLs

### LINKED ISSUE #688: V2 : remote loading of designs via proxy caching
## Expected Behavior

URLs with specific queries or hashes should be loaded by the backend, cached, and presented back to the WEB UI for rendering. This functionality is one of the most well used pieces of V1, which is missing in V2.

Examples of queries

Examples of hashes

- https://openjscad.org/#http://openjscad.org/examples/slices/tor.jscad 
- https://openjscad.org/#https://www.thingiverse.com/download:3591322

## Actual Behavior

No loading of anything.

## Steps to Reproduce the Problem

  1. Rework the above examples to V2, and post to those sites.
  2. Load the URLs into any browser
  3. ...nothing happens...

## Specifications

  - Version: V2
  - Platform: All
  - Environment: All browsers

### PR DESCRIPTION
**Pull request by z3dev**
These changes fix the loading of designs from remote URLs, using the webserver as a proxy cache for the contents of the URLs. This allows:
- URL addresses containing hashes; http://jscad.xyz#http://external.com/data/design.js
- URL addresses containing queries; http://jscad.xyz#uri=http://external.com/data/design.js
- drag and drop of URLs

Testing was performed on MacOS and Windows 10, across the following browsers
- Safari
- Chrome
- Firefox
- Edge
- Opera

Note: The installation of the backend process is required to use this functionality. An additional note was added to the [V2 Summary of Changes](https://openjscad.org/dokuwiki/doku.php?id=changes_v2).

Fixes #688 

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?
Thank you for your help in advance, much appreciated !

### CODE REVIEW

File: packages/web/src/sideEffects/http/index.js [hunk 1]
```diff
@@ -1,43 +1,35 @@
...
 const makeLogger = require('../../utils/logger')
 const getFileExtensionFromString = require('@jscad/core/utils/getFileExtensionFromString')
 
 const XMLHttpRequest = window.XMLHttpRequest
 
-/** function to create the http side effect
- * sink: input of commands that generate http requests
- * source: output of response from http requests
+// const proxyUrl = './remote.php?url='
+const proxyUrl = './remote.pl?url='
```
Comment (SimonClark) [inline packages/web/src/sideEffects/http/index.js:11]: Why .pl instead .php?  Just curious.

File: packages/web/src/sideEffects/localFs/walkFileTree.js [hunk 2]
```diff
@@ -94,11 +94,17 @@ const processItems = (items) => {
  * @returns {Promise} new promise to read and process the file
  */
 const processFile = (fileItem) => {
-  // console.log('processFile',fileItem)
+  console.log('processFile',fileItem)
```
Comment (SimonClark) [inline packages/web/src/sideEffects/localFs/walkFileTree.js:97]: Take out?

File: packages/web/remote.php [hunk 3]
```diff
@@ -12,13 +12,20 @@
 cleanUpExpired();
 
 function retrieveFile($url) {
+   // only process valid requests
+   $valid = strncmp($url, "http://", 7) || strncmp($url, "https://", 8);
+   if (! $valid) return;
```
[the remark this answers is not in the document]
Comment (z3dev) [reply packages/web/remote.php:17]: The WEB UI does nothing if there is nothing returned, i.e. no content.
Keep in mind that hackers can call this CGI as well, so no reponse is probably better.

[the remark this answers is not in the document]
Comment (z3dev) [reply packages/web/remote.php:17]: Yeah. Re-writing in JavaScript would be best. However, there's probablly some configuration required on the webserver, so for now I'll just add a new issue.

File: packages/web/src/sideEffects/http/index.js (hunk 1 above)
Comment (z3dev) [reply packages/web/src/sideEffects/http/index.js:11]: Both Perl and PHP versions are available.

The Perl version is slightly stronger on security, and the webserver is configured to run CGI Perl scripts. So, for now, let's use the Perl version.

I may make some changes to the Perl script as well, as there are more supported formats now. But this will be another set of changes.

**Review by SimonClark — APPROVED** [review]
